### ISSUE TITLE
[Bug] Script files randomly get written corrupted

### ISSUE THREAD

**Issue by BitBlitObviMormon** [TarantelTM/Recipe-GUI#3]
This might be a tough one to track down as it happens seemingly randomly. Regenerating the script seems to fix the issue, however. Sometimes when I create a recipe it generates the script incorrectly and it fails to parse correctly when loaded.

Here is an example of this kind of corruption when it occurs. The recipe takes two brown concrete powder and turns it into cobblestone. (I had to rename the extension for GitHub to accept the files):
[Broken recipe](https://github.com/TarantelTM/CraftTweaker-GUI/files/9750123/recipe-corrupted.zs.txt)
[Intended recipe](https://github.com/TarantelTM/CraftTweaker-GUI/files/9750122/recipe.zs.txt)

**Comment by TarantelTM** [comment]
The new Backend in v 0.0.2 should work better to generate the Code from all Slots.

**Comment by BitBlitObviMormon** [comment]
Cool. I'll close the issue for now; if it crops up again I'll open a new one.
